let card_number = [
                "PICK SOMEONE AND GUESS THE COLOR OF THEIR UNDERWEAR. IF YOU GUESS CORRECTLY, THEY DRINK, OTHERWISE YOU DRINK.",
                "THE PERSON WITH THE LEAST INSTAGRAM FOLLOWERS DRINKS.",
                "GIVE AN ORDER UNTIL THE NEXT TURN",
                "STARTING FROM YOU, THINK OF A WORD THAT ENDS WITH 'NE'. THE ONE WHO REPEATS A WORD OR PAUSES SHOULD DRINK 2",
                "PICK A PERSON TO DRINK.",
                "EVERYONE WHO IS TALLER THAN YOU DRINKS.",
                "EVERYONE WEARING JEANS DRINKS.",
                "PICK A WORD. EVERYONE TAKES TURNS SAYING A WORD THAT RHYMES. THE PERSON THAT HESITATES OR REPEATS A WORD DRINKS.",
                "STARTING FROM YOU, GIVE A KIND OF CHEESE. THE ONE WHO REPEATS OR PAUSES SHOULD DRINK 2",
                "TELL US YOUR BODY COUNT",
                "TRUTH OR DARE OR DRINK. YOUR RIGHT WILL ASK OR DARE YOU",
                "NEXT CARD PLEASE",
                "EVERYONE VOTES ON WHO IS THE BIGGEST ALCOHOLIC. THAT PERSON DRINKS AND ALSO PICKS ANOTHER PERSON TO DRINK.",
                "YOUR LEFT DRINKS",
                "YOUR RIGHT DRINKS",
                "ALL SHOULD DRINK!",
                "NEXT CARD PLEASE",
                "STARTING FROM YOU. GIVE A KIND OF ANIMAL. THE ONE WHO REPEATS OR PAUSES SHOULD DRINK 2",
                "STARTING FROM YOU. GIVE A KIND OF MOVIE. THE ONE WHO REPEATS OR PAUSES SHOULD DRINK 2",
                "YOU DRINK.",
                "THE PERSON AFTER YOU CAN ASK YOU ANY QUESTION. YOU CAN EITHER ANSWER TRUTHFULLY OR REFUSE TO ANSWER AND DRINK.",
                "DRINK FOR EVERY SIBLING YOU HAVE.",
                "PICK SOMEONE TO PLAY ROCK, PAPER, SCISSORS WITH. LOSER DRINKS.",
                "GIVE A CONFESSION OR DRINK.",
                "TALK WITH AN ACCENT UNTIL NECT TURN. IF CAUGHT NOT SPEAKING WITH THE ACCENT, YOU DRINK.",
                "ANSWER A 'WOULD YOU RATHER' QUESTION OR DRINK.",
                "PLAY A 'NEVER HAVE I EVER'",
                "EVERYONE WHO IS SHORTER THAN YOU DRINKS.",
                "THE PERSON WHO MOST RECENTLY USED THE BATHROOM DRINKS.",
                "FLIP A COIN. IF IT'S HEADS, YOU DRINK. IS IT'S TAILS, EVERYONE ELSE DRINKS.",
                "EVERYONE WHO IS SINGLE DRINKS.",
                "YOU DRINK.",
                "STARTING WITH YOU, TAKE TURNS NAMING A COLOR. CONTINUE UNTIL SOMEONE HESITATES OR REPEATS A COLOR. THAT PERSON DRINKS.",
                "IMITATE ANOTHER PLAYER. FIRST PERSON TO CORRECTLY GUESS SHOULD PICK SOMEONE TO DRINK",
                "COUPLES DRINK",
                "EVERYONE BUT YOU DRINKS",
                "IMITATE A HERO. FIRST PERSON TO CORRECTLY GUESS SHOULD PICK SOMEONE TO DRINK",
                "PERSONS WITH TATTOOS DRINK",
                "PERSON WITH THE LONGEST SURNAME DRINKS",
                "PONYTAILED HAIR PEOPLE DRINK!",
                "CURLY HAIRED PEOPLE DRINK!",
                "TELL A JOKE. IF NO ONE LAUGHS, YOU DRINK",
                "STARTING WITH YOU, TAKE TURNS NAMING A FOOD. CONTINUE UNTIL SOMEONE HESITATES OR REPEATS A WORD. THAT PERSON DRINKS.",
                "LAST PERSON TO STICK OUT THEIR TONGUE DRINKS",
                "TAKE TURNS NAMING A SEX POSITION. THE PERSON WHO REPEATS OR PAUSES SHOULD DRINK 2",
                "VIRGINS DRINK!",
                "DRINK IF YOU HAVE FAKED AN ORGASM",
                "SING THE 'NOSI BA LASI'. THE PERSON WHO HAS THE SHORTEST 'SINO' SHOULD DRINK 3!",
                "STARTING WITH YOU, TAKE TURNS NAMING A COUNTRY. CONTINUE UNTIL SOMEONE HESITATES OR REPEATS A WORD. THAT PERSON DRINKS.",
                "YOU DRINK",
                "NEXT CARD PLEASE",
                "ON THE COUNT OF THREE, STAND UP! THE LAST PERSON TO STAND DRINKS 2",
                "WITHOUT TOUCHING ANYTHING, BALANCE YOUR ONE LEG. LAST PERSON TO FALL PICK SOMEONE TO DRINK",
                "EVERYONE WEARING WHITE SHIRT DRINKS",
                "STARTING WITH YOU, TAKE TURNS NAMING AN STD. CONTINUE UNTIL SOMEONE HESITATES OR REPEATS A WORD. THAT PERSON DRINKS.",
                "THE FLOOR IS LAVA! LAST PERSON STILL ON THE FLOOR DRINKS",
                "THE PERSON ADJACENT TO YOU DRINKS",
                "DRINK WITHOUT CHASER",
                "PICK A WORD. EVERYONE TAKES TURNS SAYING A WORD THAT RHYMES. THE PERSON THAT HESITATES OR REPEATS A WORD DRINKS.",
                "EVERYONE WHO CAN'T TOUCH THEIR TOES WITHOUT BENDING KNEES, DRINK!",
                "NAME A KPOP SONG. TAKE TURNS UNTIL SOMEONE REPEATS OR PAUSES",
                "ANYONE WHO IS POINTED AT, DRINKS",
                "PERSONS TO YOUR LEFT AND RIGHT DRINK",
                "LAST PERSON TO PUT HANDS IN THE AIR DRINKS!",
                "MAKE A RULE UNTIL THE NEXT TURN",
                "CHOOSE A CATEGORY. TAKE TURNS NAMING THAT ITEM. THE PERSON WHO REPEATS OR PAUSES SHOULD DRINK",
                "KEEP YOUR EYE CLOSED UNTIL THE NEXT 2 ROUNDS. IF YOU FAIL, DRINK 3",
                "CHALLENGE 2 PEOPLE TO DO PUSH-UP, LOSERS TAKE 2 DRINKS EACH",
                "HOLD YOUR BREATHE FOR 40 SECONDS. IF YOU FAIL, YOU DRINK",
                "EVERYONE MUST REMAIN SILENT UNTIL THE NEXT TURN. PERSON WHO FAILS SHOULD DRINK 2",
                "DARE A PERSON OF YOUR CHOICE TO DO SOMETHING, IF THEY REFUSE, THEY SHOULD DRINK",
                "RECITE A POEM. THE LAST WORD SHOULD BE THE STARTING WORD UNTIL THE NEXT TURN",
                "NAME A HOLLYWOOD SINGER. THE PERSONS WHO REPEATS OR PAUSES SHOULD DRINK",
                "NAME A GAME. THE PERSONS WHO REPEATS OR PAUSES SHOULD DRINK",
                "NAME A FRUIT/VEGGIE FROM BAHAY KUBO. THE PERSON WHO REPEATS OR PAUSES SHOULD DRINK",
                "THE PERSON AFTER YOU CAN ASK YOU ANY QUESTION. YOU CAN EITHER ANSWER TRUTHFULLY OR REFUSE TO ANSWER AND DRINK.",
                "LAST PERSON TO STICK OUT THEIR TONGUE DRINKS",
                "PERSONS WHO HAVE SENT A NUDE BEFORE, DRINKS",
                "THE PERSON AFTER YOU DRINKS",
                "EVERYONE VOTES FOR A PERSON TO DRINK",
                "LAST PERSON TO CLAP THEIR HANDS DRINK",
                "THE PERSON BEFORE YOU DRINKS",
                "STARTING WITH YOU, TAKE TURNS NAMING AN ALCOHOL. CONTINUE UNTIL SOMEONE HESITATES OR REPEATS A WORD. THAT PERSON DRINKS.",
                "STARTING WITH YOU, TAKE TURNS NAMING A HOROSCOPE. CONTINUE UNTIL SOMEONE HESITATES OR REPEATS A WORD. THAT PERSON DRINKS.",
                "KEEP YOUR EYES CLOSED UNTIL IT'S YOUR TURN AGAIN. IF YOU FAIL, YOU DRINK 2",
                "THINK OF A WORD THAT STARTS WITH A VOWEL. TAKE TURNS UNTIL SOMEONE MESS UP OR REPEATS.",
                "ON THE COUNT OF 3, EVERYONE HOLDS UP EITHER A THUMB DOWN OR UP. EVERYONE THAT DOES AN OPPOSITE TO YOU SHOULD DRINK",
                "PICK AN ANIMAL AND ACT OUT THIS ANIMAL. FIRST PERSON TO GUESS SHOULD PICK SOMEONE TO DRINK",
                "ASK ANOTHER PLAYER A TRUE OR FALSE QUESTION ABOUT YOURSELF. IF THEY ANSWER YOU CORRECTLY, YOU DRINK.",
                "EVERYONE WEARING THE SAME SHIRT AS YOU DRINKS",
                "TELL 2 TRUTHS AND A LIE. ANYONE CAN ANSWER. IF THE FIRST ANSWER IS CORRECT, YOU DRINK. OTHERWISE, HE/SHE DRINKS",
                "HUM A SONG OF YOUR CHOICE. IF SOMEONE GUESSES IT CORRECTLY PICKS SOMEONOE TO DRINK",
                "YOU CANNOT MAKE EYE CONTACT WITH ANYONE UNTIL THE NEXT TURN. IF YOU FAIL, YOU DRINK 2",
                "EVERYONE BUT YOU DRINKS",
                "PICK SOMEONE TO DRINK WITH YOU",
                "FREE PASS!",
                "GIVE A CONFESSION OR DRINK",
                "MAKE YOUR BEST ORGASM NOISE OR DRINK 2",
                "SLAP SOMEONE IN THE GAME OR DRINK",
                "EVERYONE MUST KEEP A STRAIGHT FACE. FIRST PERSON TO LAUGH SHOULD DRINK 2",
                "EVERYONE MUST SPEAK IN ENGLISH UNTIL THE NEXT TURN. PERSON WHO FAILS SHOULD DRINK 3",
                "ARM WRESTLE WITH YOUR RIGHT. LOSER SHOULD DRINK 2",
                "ARM WRESTLE WITH YOUR LEFT. LOSER SHOULD DRINK 2"
              ];

let suit = ["Diamonds", "Spades", "Hearts", "Clubs"];


$(".card").addClass("default");

$(".button").click(function(e) {
  e.preventDefault();
  randomCard();
  $("audio#card_effect")[0].play();
  $(".card").removeClass("default");
});
randomCard();

function randomCard() {

  let card_number_length = card_number.length;
  let random_card_number = Math.floor(Math.random() * card_number_length);
  let suit_length = suit.length;
  let random_suit_number = Math.floor(Math.random() * suit_length);
  let final_suit = suit[random_suit_number];

  $("p").text(card_number[random_card_number]);
  $("div").removeClass("suit-diamonds suit-spades suit-hearts suit-clubs");
 
  switch (final_suit) {
    case "Diamonds":
      $("div").addClass("suit-diamonds");
      break;
    case "Spades":
      $("div").addClass("suit-spades");
      break;
    case "Hearts":
      $("div").addClass("suit-hearts");
      break;
    case "Clubs":
      $("div").addClass("suit-clubs");
      break;
  }
}
